# Generated by Django 4.2 on 2023-05-20 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('user_key', models.CharField(max_length=30, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='AdminKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_key', models.CharField(max_length=50, verbose_name='admin_key')),
            ],
            options={
                'db_table': 'admin_key',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('difficulty_name', models.CharField(max_length=20, verbose_name='difficulty')),
                ('words', models.JSONField()),
                ('time_limit', models.IntegerField()),
                ('points_per_question', models.IntegerField()),
                ('maxpoints', models.IntegerField()),
                ('answered', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('words1', models.JSONField()),
            ],
            options={
                'db_table': 'difficulty',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('topic_name', models.CharField(max_length=100, verbose_name='topic_name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=20, verbose_name='image_name')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.difficulty')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
        migrations.AddField(
            model_name='difficulty',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.topics'),
        ),
    ]
